#!/bin/bash

set -e

cd ~/unique-race
git fetch
git reset --hard origin/unique-race
cmake -Bbuild -GNinja -DCLIENT=OFF -DMYSQL=ON
cmake --build build -- DDNet-Server
mv build/DDNet-Server ~/unique-kit
